/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014 Zimbra, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: http://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.
 * All portions of the code are Copyright (C) 2014 Zimbra, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('eu',{
"Cut": "Ebaki",
"Heading 5": "5. goiburua",
"Header 2": "2. goiburua",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Zure arakatzaileak ez du onartzean arbela zuzenean erabiltzea. Horren ordez, erabili Ktrl + X\/C\/V lasterbideak.",
"Heading 4": "4. goiburua",
"Div": "Div",
"Heading 2": "2. goiburua",
"Paste": "Itsatsi",
"Close": "Itxi",
"Font Family": "Letra-tipoaren familia",
"Pre": "Pre",
"Align right": "Lerrokatu eskuinean",
"New document": "Dokumentu berria",
"Blockquote": "Aipamena",
"Numbered list": "Zenbakidun zerrenda",
"Heading 1": "1. goiburua",
"Headings": "Goiburuak",
"Increase indent": "Handitu koska",
"Formats": "Formatuak",
"Headers": "Goiburuak",
"Select all": "Hautatu guztiak",
"Header 3": "3. goiburua",
"Blocks": "Blokeoak",
"Undo": "Desegin",
"Strikethrough": "Marratua",
"Bullet list": "Buletdun zerrenda",
"Header 1": "1. goiburua",
"Superscript": "Goi-indizea",
"Clear formatting": "Garbitu formatua",
"Font Sizes": "Letra-tamainak",
"Subscript": "Azpiindizea",
"Header 6": "6. goiburua",
"Redo": "Berregin",
"Paragraph": "Paragrafoa",
"Ok": "Ados",
"Bold": "Lodia",
"Code": "Kodea",
"Italic": "Etzana",
"Align center": "Lerrokatu erdian",
"Header 5": "5. goiburua",
"Heading 6": "6. goiburua",
"Heading 3": "3. goiburua",
"Decrease indent": "Txikitu koska",
"Header 4": "4. goiburua",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Itsasteko aukera testu arrunt gisa dago orain. Edukia testu arrunt gisa itsatsiko da aukera hau desaktibatzen duzun arte.",
"Underline": "Azpimarra",
"Cancel": "Utzi",
"Justify": "Justifikatu",
"Inline": "Txertatu gorputzean",
"Copy": "Kopiatu",
"Align left": "Lerrokatu ezkerrean",
"Visual aids": "Laguntza bisualak",
"Lower Greek": "Behe-grekoa",
"Square": "Karratua",
"Default": "Lehenetsia",
"Lower Alpha": "Behe-alfa",
"Circle": "Zirkulua",
"Disc": "Diskoa",
"Upper Alpha": "Goi-alfa",
"Upper Roman": "Goi-erromatarra",
"Lower Roman": "Behe-erromatarra",
"Name": "Izena",
"Anchor": "Aingura",
"You have unsaved changes are you sure you want to navigate away?": "Gorde gabeko aldaketak dituzu. Ziur irten nahi duzula?",
"Restore last draft": "Leheneratu azken zirriborroa",
"Special character": "Karaktere berezia",
"Source code": "Iturburu-kodea",
"B": "B",
"R": "R",
"G": "G",
"Color": "Kolorea",
"Right to left": "Eskuinetik ezkerrera",
"Left to right": "Ezkerretik eskuinera",
"Emoticons": "Emotikonoak",
"Robots": "Robotak",
"Document properties": "Dokumentuaren propietateak",
"Title": "Izena",
"Keywords": "Gako-hitzak",
"Encoding": "Kodeketa",
"Description": "Azalpena",
"Author": "Egilea",
"Fullscreen": "Pantaila osoa",
"Horizontal line": "Marra horizontala",
"Horizontal space": "Zuriune horizontala",
"Insert\/edit image": "Txertatu\/Editatu irudia",
"General": "Orokorra",
"Advanced": "Aurreratua",
"Source": "Jatorria",
"Border": "Ertza",
"Constrain proportions": "Mugatu proportzioak",
"Vertical space": "Zuriune bertikala",
"Image description": "Irudiaren azalpena",
"Style": "Estiloa",
"Dimensions": "Neurriak",
"Insert image": "Txertatu irudia",
"Zoom in": "Handitu",
"Contrast": "Kontrastea",
"Back": "Atzera",
"Gamma": "Gamma",
"Flip horizontally": "Irauli horizontalki",
"Resize": "Aldatu tamaina",
"Sharpen": "Areagotu",
"Zoom out": "Txikitu",
"Image options": "Irudiaren aukerak",
"Apply": "Aplikatu",
"Brightness": "Distira",
"Rotate clockwise": "Biratu eskuinera",
"Rotate counterclockwise": "Biratu ezkerrera",
"Edit image": "Editatu irudia",
"Color levels": "Kolore-mailak",
"Crop": "Ebaki",
"Orientation": "Orientazioa",
"Flip vertically": "Irauli bertikalki",
"Invert": "Alderantzikatu",
"Insert date\/time": "Txertatu data\/ordua",
"Remove link": "Kendu esteka",
"Url": "URLa",
"Text to display": "Bistaratzeko testua",
"Anchors": "Aingurak",
"Insert link": "Txertatu esteka",
"New window": "Leiho berria",
"None": "Bat ere ez",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Dirudienez, idatzi duzun URLa kanpoko esteka da. Beharrezko http:\/\/ aurrizkia gehitu nahi duzu?",
"Target": "Helburua",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Dirudienez, idatzi duzun URLa helbide elektronikoa da. Beharrezko mailto: aurrizkia gehitu nahi duzu?",
"Insert\/edit link": "Txertatu\/Editatu esteka",
"Insert\/edit video": "Txertatu\/Editatu bideoa",
"Poster": "Argitaratzailea",
"Alternative source": "Ordezko jatorria",
"Paste your embed code below:": "Itsatsi kapsulatzeko kodea behean:",
"Insert video": "Txertatu bideoa",
"Embed": "Kapsulatu",
"Nonbreaking space": "Zuriune zatiezina",
"Page break": "Orri-jauzia",
"Paste as text": "Itsatsi testu gisa",
"Preview": "Aurrebista",
"Print": "Inprimatu",
"Save": "Gorde",
"Could not find the specified string.": "Ezin izan da aurkitu zehaztutako katea.",
"Replace": "Ordeztu",
"Next": "Hurrengoa",
"Whole words": "Hitz osoak",
"Find and replace": "Bilatu eta ordeztu",
"Replace with": "Ordeztu honekin:",
"Find": "Bilatu",
"Replace all": "Ordeztu guztiak",
"Match case": "Bereizi maiuskulak eta minuskulak",
"Prev": "Aurrekoa",
"Spellcheck": "Zuzendu ortografia",
"Finish": "Amaitu",
"Ignore all": "Egin ez ikusi guztiei",
"Ignore": "Egin ez ikusi",
"Add to Dictionary": "Gehitu hiztegian",
"Insert row before": "Txertatu errenkada aurretik",
"Rows": "Errenkadak",
"Height": "Altuera",
"Paste row after": "Itsatsi errenkada ondoren",
"Alignment": "Lerrokatzea",
"Border color": "Ertzaren kolorea",
"Column group": "Zutabe multzoa",
"Row": "Errenkada",
"Insert column before": "Txertatu zutabea aurretik",
"Split cell": "Zatitu gelaxka",
"Cell padding": "Gelaxken betegarria",
"Cell spacing": "Gelaxka arteko tartea",
"Row type": "Lerro mota",
"Insert table": "Txertatu taula",
"Body": "Gorputza",
"Caption": "Epigrafea",
"Footer": "Orri-oina",
"Delete row": "Ezabatu errenkada",
"Paste row before": "Itsatsi errenkada aurretik",
"Scope": "Esparrua",
"Delete table": "Ezabatu taula",
"H Align": "Lerrokatze horizontala",
"Top": "Goian",
"Header cell": "Goiburuko gelaxka",
"Column": "Zutabea",
"Row group": "Errenkada multzoa",
"Cell": "Gelaxka",
"Middle": "Erdian",
"Cell type": "Gelaxka mota",
"Copy row": "Kopiatu errenkada",
"Row properties": "Errenkadaren propietateak",
"Table properties": "Taularen propietateak",
"Bottom": "Behean",
"V Align": "Lerrokatze bertikala",
"Header": "Goiburua",
"Right": "Eskuinean",
"Insert column after": "Txertatu zutabea ondoren",
"Cols": "Zutabeak",
"Insert row after": "Txertatu errenkada ondoren",
"Width": "Zabalera",
"Cell properties": "Gelaxkaren propietateak",
"Left": "Ezkerrean",
"Cut row": "Ebaki errenkada",
"Delete column": "Ezabatu zutabea",
"Center": "Erdian",
"Merge cells": "Bateratu gelaxkak",
"Insert template": "Txertatu txantiloia",
"Templates": "Txantiloiak",
"Background color": "Atzeko kolorea",
"Custom...": "Pertsonalizatua...",
"Custom color": "Kolore pertsonalizatua",
"No color": "Kolorerik gabe",
"Text color": "Testuaren kolorea",
"Show blocks": "Erakutsi blokeoak",
"Show invisible characters": "Erakutsi ezkutuko karaktereak",
"Words: {0}": "Hitzak: {0}",
"Insert": "Txertatu",
"File": "Fitxategia",
"Edit": "Editatu",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Testu aberastuko area. Sakatu ALT-F9 menua ikusteko. Sakatu ALT-F10 tresna-barra ikusteko. Sakatu ALT-0 laguntza ikusteko",
"Tools": "Tresnak",
"View": "Ikusi",
"Table": "Taula",
"Format": "Formatua"
});
