/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n("fr_FR",{
"Cut": "Couper",
"Heading 5": "Titre 5",
"Header 2": "En-t\u00eate 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Ce navigateur ne supporte pas la copie directe vers le Presse-papiers. Utilisez plut\u00f4t les raccourcis Ctrl+X\/C\/V.",
"Heading 4": "Titre 4",
"Div": "Div",
"Heading 2": "Titre 2",
"Paste": "Coller",
"Close": "Fermer",
"Font Family": "Famille de polices",
"Pre": "Pre",
"Align right": "Aligner \u00e0 droite",
"New document": "Nouveau document",
"Blockquote": "Citation",
"Numbered list": "Liste num\u00e9rot\u00e9e",
"Heading 1": "Titre 1",
"Headings": "Titres",
"Increase indent": "Augmenter le retrait",
"Formats": "Formats",
"Headers": "En-t\u00eates",
"Select all": "S\u00e9lectionner tout ",
"Header 3": "En-t\u00eate 3",
"Blocks": "Blocs",
"Undo": "D\u00e9faire",
"Strikethrough": "Barr\u00e9",
"Bullet list": "Liste \u00e0 puces",
"Header 1": "En-t\u00eate 1",
"Superscript": "Exposant",
"Clear formatting": "Effacer la mise en forme",
"Font Sizes": "Tailles de police",
"Subscript": "Indice",
"Header 6": "En-t\u00eate 6",
"Redo": "Refaire",
"Paragraph": "Paragraphe",
"Ok": "OK",
"Bold": "Gras",
"Code": "Code",
"Italic": "Italique",
"Align center": "Centr\u00e9",
"Header 5": "En-t\u00eate 5",
"Heading 6": "Titre 6",
"Heading 3": "Titre 3",
"Decrease indent": "Diminuer le retrait",
"Header 4": "En-t\u00eate 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "La fonctionnalit\u00e9 Coller est en mode Texte brut. Les contenus seront coll\u00e9s sans leur mise en forme jusqu'\u00e0 ce que vous inversiez ce r\u00e9glage.",
"Underline": "Soulign\u00e9",
"Cancel": "Annuler",
"Justify": "Justifier",
"Inline": "En ligne",
"Copy": "Copier",
"Align left": "Aligner \u00e0 gauche",
"Visual aids": "Aides visuelle",
"Lower Greek": "Grec minuscule",
"Square": "Carr\u00e9",
"Default": "Par d\u00e9faut",
"Lower Alpha": "Alpha minuscule",
"Circle": "Cercle",
"Disc": "Disque",
"Upper Alpha": "Alpha majuscule",
"Upper Roman": "Romain majuscule",
"Lower Roman": "Romain minuscule",
"Name": "Nom",
"Anchor": "Ancre",
"You have unsaved changes are you sure you want to navigate away?": "Certaines modifications n'ont pas \u00e9t\u00e9  enregistr\u00e9es. Voulez-vous vraiment quitter cette page ?",
"Restore last draft": "Restaurer le dernier brouillon",
"Special character": "Caract\u00e8re sp\u00e9cial",
"Source code": "Code source",
"B": "B",
"R": "R",
"G": "G",
"Color": "Couleur",
"Right to left": "De droite \u00e0 gauche",
"Left to right": "De gauche \u00e0 droite",
"Emoticons": "\u00c9motic\u00f4nes",
"Robots": "Robots",
"Document properties": "Propri\u00e9t\u00e9s du document",
"Title": "Titre",
"Keywords": "Mots-cl\u00e9s",
"Encoding": "Encodage",
"Description": "Description",
"Author": "Auteur",
"Fullscreen": "Plein \u00e9cran",
"Horizontal line": "Ligne horizontale",
"Horizontal space": "Espacement horizontal",
"Insert\/edit image": "Ins\u00e9rer\/Modifier une photo",
"General": "G\u00e9n\u00e9ralit\u00e9s",
"Advanced": "Avanc\u00e9",
"Source": "Source",
"Border": "Bordure",
"Constrain proportions": "Conserver les proportions",
"Vertical space": "Espacement vertical",
"Image description": "Description de la photo",
"Style": "Style",
"Dimensions": "Dimensions",
"Insert image": "Ins\u00e9rer une photo",
"Zoom in": "Zoom avant",
"Contrast": "Contraste",
"Back": "Pr\u00e9c\u00e9dent",
"Gamma": "Gamma",
"Flip horizontally": "Retourner horizontalement",
"Resize": "Redimensionner",
"Sharpen": "Affiner",
"Zoom out": "Zoom arri\u00e8re",
"Image options": "Options de la photo",
"Apply": "Appliquer",
"Brightness": "Luminosit\u00e9",
"Rotate clockwise": "Rotation horaire",
"Rotate counterclockwise": "Rotation anti-horaire",
"Edit image": "Modifier la photo",
"Color levels": "Niveaux de couleur",
"Crop": "Rogner",
"Orientation": "Orientation",
"Flip vertically": "Retourner verticalement",
"Invert": "Inverser",
"Insert date\/time": "Ins\u00e9rer date\/heure",
"Remove link": "Annuler le lien",
"Url": "URL",
"Text to display": "Texte \u00e0 afficher",
"Anchors": "Ancres",
"Insert link": "Ins\u00e9rer un lien",
"New window": "Nouvelle fen\u00eatre",
"None": "N\u00e9ant",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Apparemment, l'URL que vous avez entr\u00e9e correspond \u00e0 un lien externe. Voulez-vous ajouter le pr\u00e9fixe http:\/\/ (requis) ?",
"Target": "Cible",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Apparemment, l'URL que vous avez entr\u00e9e correspond \u00e0 une adresse mail. Voulez-vous ajouter le pr\u00e9fixe mailto: (requis) ?",
"Insert\/edit link": "Ins\u00e9rer\/modifier un lien",
"Insert\/edit video": "Ins\u00e9rer\/modifier une vid\u00e9o",
"Poster": "Auteur du message",
"Alternative source": "Autre source",
"Paste your embed code below:": "Collez votre code d'int\u00e9gration ci-dessous :",
"Insert video": "Ins\u00e9rer une vid\u00e9o",
"Embed": "Int\u00e9grer",
"Nonbreaking space": "Espace ins\u00e9cable",
"Page break": "Saut de page",
"Paste as text": "Coller comme texte",
"Preview": "Aper\u00e7u",
"Print": "Imprimer",
"Save": "Enregistrer",
"Could not find the specified string.": "La cha\u00eene sp\u00e9cifi\u00e9e est introuvable.",
"Replace": "Remplacer",
"Next": "Suivant",
"Whole words": "Mots entiers",
"Find and replace": "Rechercher et remplacer",
"Replace with": "Remplacer par",
"Find": "Rechercher",
"Replace all": "Tout remplacer",
"Match case": "Respecter la casse",
"Prev": "Pr\u00e9c\u00e9dent",
"Spellcheck": "V\u00e9rifier l'orthographe",
"Finish": "Terminer",
"Ignore all": "Tout ignorer",
"Ignore": "Ignorer",
"Add to Dictionary": "Ajouter dans le dictionnaire",
"Insert row before": "Ins\u00e9rer une ligne avant",
"Rows": "Lignes",
"Height": "Hauteur",
"Paste row after": "Coller la ligne apr\u00e8s",
"Alignment": "Alignement",
"Border color": "Couleur de la bordure",
"Column group": "Groupe de colonnes",
"Row": "Ligne",
"Insert column before": "Ins\u00e9rer une colonne avant",
"Split cell": "Diviser la cellule",
"Cell padding": "Remplissage des cellules",
"Cell spacing": "Espace entre cellules",
"Row type": "Type de ligne",
"Insert table": "Ins\u00e9rer un tableau",
"Body": "Corps de texte",
"Caption": "L\u00e9gende",
"Footer": "Pied de page",
"Delete row": "Supprimer la ligne",
"Paste row before": "Coller la ligne avant",
"Scope": "\u00c9tendue",
"Delete table": "Supprimer le tableau",
"H Align": "Alignement H",
"Top": "Haut",
"Header cell": "Cellule d'en-t\u00eate",
"Column": "Colonne",
"Row group": "Groupe de lignes",
"Cell": "Cellule",
"Middle": "Milieu",
"Cell type": "Type de cellule",
"Copy row": "Copier la ligne",
"Row properties": "Propri\u00e9t\u00e9s de la ligne",
"Table properties": "Propri\u00e9t\u00e9s du tableau",
"Bottom": "Bas",
"V Align": "Alignement V",
"Header": "En-t\u00eate",
"Right": "Droite",
"Insert column after": "Ins\u00e9rer une colonne apr\u00e8s",
"Cols": "Colonnes",
"Insert row after": "Ins\u00e9rer une ligne apr\u00e8s",
"Width": "Largeur",
"Cell properties": "Propri\u00e9t\u00e9s de la cellule",
"Left": "Gauche",
"Cut row": "Couper la ligne",
"Delete column": "Supprimer la colonne",
"Center": "Centr\u00e9",
"Merge cells": "Fusionner les cellules",
"Insert template": "Ins\u00e9rer un th\u00e8me",
"Templates": "Th\u00e8mes",
"Background color": "Couleur du fond ",
"Custom...": "Personnalis\u00e9...",
"Custom color": "Couleur personnalis\u00e9e",
"No color": "Aucune couleur",
"Text color": "Couleur du texte",
"Show blocks": "Afficher les blocs",
"Show invisible characters": "Afficher les caract\u00e8res invisibles",
"Words: {0}": "Mots : {0}",
"Insert": "Ins\u00e9rer",
"File": "Fichier",
"Edit": "Modifier",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zone de Texte riche. Alt+F9 pour afficher le menu. Alt+F10 pour afficher la barre d'outils. Alt+0 pour afficher l'aide.",
"Tools": "Outils",
"View": "Affichage",
"Table": "Tableau",
"Format": "Format"
});

