/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n("id",{
"Cut": "Potong",
"Heading 5": "Judul 5",
"Header 2": "Header 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser Anda tidak mendukung akses langsung ke clipboard. Silakan gunakan pintasan keyboard Ctrl+X\/C\/V.",
"Heading 4": "Judul 4",
"Div": "Div",
"Heading 2": "Judul 2",
"Paste": "Tempel",
"Close": "Tutup",
"Font Family": "Jenis Huruf",
"Pre": "Pre",
"Align right": "Rata kanan",
"New document": "Dokumen baru",
"Blockquote": "Kutipan",
"Numbered list": "Daftar bernomor",
"Heading 1": "Judul 1",
"Headings": "Judul",
"Increase indent": "Tambah indentasi",
"Formats": "Format",
"Headers": "Header",
"Select all": "Pilih semua",
"Header 3": "Header 3",
"Blocks": "Blok",
"Undo": "Urungkan",
"Strikethrough": "Coret",
"Bullet list": "Daftar bersimbol",
"Header 1": "Header 1",
"Superscript": "Superskrip",
"Clear formatting": "Hapus format",
"Font Sizes": "Ukuran Huruf",
"Subscript": "Subskrip",
"Header 6": "Header 6",
"Redo": "Ulang",
"Paragraph": "Paragraf",
"Ok": "Ok",
"Bold": "Tebal",
"Code": "Kode",
"Italic": "Miring",
"Align center": "Rata tengah",
"Header 5": "Header 5",
"Heading 6": "Judul 6",
"Heading 3": "Judul 3",
"Decrease indent": "Turunkan indentasi",
"Header 4": "Header 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Penempelan sekarang dalam mode teks biasa. Konten sekarang akan ditempelkan sebagai teks biasa sampai Anda mengubah pilihan ini.",
"Underline": "Garis bawah",
"Cancel": "Batalkan",
"Justify": "Ratakan",
"Inline": "Sebaris",
"Copy": "Salin",
"Align left": "Rata kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Huruf Kecil Yunani",
"Square": "Kotak",
"Default": "Default",
"Lower Alpha": "Huruf Kecil",
"Circle": "Lingkaran",
"Disc": "Cakram",
"Upper Alpha": "Huruf Besar",
"Upper Roman": "Huruf Besar Romawi",
"Lower Roman": "Huruf Kecil Romawi",
"Name": "Nama",
"Anchor": "Jangkar",
"You have unsaved changes are you sure you want to navigate away?": "Anda memiliki perubahan yang belum disimpan, yakin ingin keluar?",
"Restore last draft": "Pulihkan draft terakhir",
"Special character": "Karakter spesial",
"Source code": "Kode sumber",
"B": "B",
"R": "R",
"G": "G",
"Color": "Warna",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Properti dokumen",
"Title": "Judul",
"Keywords": "Kata kunci",
"Encoding": "Pengodean",
"Description": "Deskripsi",
"Author": "Penulis",
"Fullscreen": "Layar penuh",
"Horizontal line": "Garis horizontal",
"Horizontal space": "Spasi horizontal",
"Insert\/edit image": "Sisipkan\/edit gambar",
"General": "Umum",
"Advanced": "Canggih",
"Source": "Sumber",
"Border": "Batas",
"Constrain proportions": "Samakan proporsi",
"Vertical space": "Spasi vertikal",
"Image description": "Deskripsi gambar",
"Style": "Gaya",
"Dimensions": "Dimensi",
"Insert image": "Sisipkan gambar",
"Zoom in": "Perbesar",
"Contrast": "Kontras",
"Back": "Kembali",
"Gamma": "Gamma",
"Flip horizontally": "Balik horizontal",
"Resize": "Ubah ukuran",
"Sharpen": "Ketajaman",
"Zoom out": "Perkecil",
"Image options": "Opsi gambar",
"Apply": "Terapkan",
"Brightness": "Kecerahan",
"Rotate clockwise": "Putar searah jarum jam",
"Rotate counterclockwise": "Putar berlawanan jarum jam",
"Edit image": "Edit gambar",
"Color levels": "Tingkat warna",
"Crop": "Pangkas",
"Orientation": "Orientasi",
"Flip vertically": "Balik vertikal",
"Invert": "Kebalikan",
"Insert date\/time": "Sisipkan tanggal\/waktu",
"Remove link": "Buang tautan",
"Url": "Url",
"Text to display": "Teks yang ditampilkan",
"Anchors": "Jangkar",
"Insert link": "Sisipkan tautan",
"New window": "Jendela baru",
"None": "Tidak Ada",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL yang Anda masukkan sepertinya tautan eksternal. Apakah Anda ingin menambahkan prefiks http:\/\/ yang dibutuhkan?",
"Target": "Target",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL yang Anda masukkan sepertinya alamat email. Apakah Anda ingin menambahkan prefiks mailto: yang dibutuhkan?",
"Insert\/edit link": "Sisip\/edit tautan",
"Insert\/edit video": "Sisip\/edit video",
"Poster": "Penulis",
"Alternative source": "Sumber alternatif",
"Paste your embed code below:": "Tempel kode yang dilekatkan di bawah ini:",
"Insert video": "Sisipkan video",
"Embed": "Dilekatkan",
"Nonbreaking space": "Spasi tanpa pisah baris",
"Page break": "Pemisah halaman",
"Paste as text": "Tempel sebagai teks",
"Preview": "Pratinjau",
"Print": "Cetak",
"Save": "Simpan",
"Could not find the specified string.": "Tidak dapat menemukan string yang ditentukan.",
"Replace": "Ganti",
"Next": "Berikutnya",
"Whole words": "Kata utuh",
"Find and replace": "Cari dan ganti",
"Replace with": "Ganti dengan",
"Find": "Cari",
"Replace all": "Ganti semua",
"Match case": "Samakan besar kecil huruf",
"Prev": "Sebelumnya",
"Spellcheck": "Periksa ejaan",
"Finish": "Selesai",
"Ignore all": "Abaikan semua",
"Ignore": "Abaikan",
"Add to Dictionary": "Tambahkan ke Kamus",
"Insert row before": "Sisipkan baris sebelum",
"Rows": "Baris",
"Height": "Tinggi",
"Paste row after": "Tempel baris setelah",
"Alignment": "Perataan",
"Border color": "Warna batas",
"Column group": "Kelompok kolom",
"Row": "Baris",
"Insert column before": "Sisipkan kolom sebelum",
"Split cell": "Bagi sel",
"Cell padding": "Padding sel",
"Cell spacing": "Spasi sel",
"Row type": "Tipe baris",
"Insert table": "Sisipkan tabel",
"Body": "Isi",
"Caption": "Uraian",
"Footer": "Footer",
"Delete row": "Hapus baris",
"Paste row before": "Tempel baris sebelum",
"Scope": "Lingkup",
"Delete table": "Hapus tabel",
"H Align": "Rata Samping",
"Top": "Atas",
"Header cell": "Sel header",
"Column": "Kolom",
"Row group": "Kelompok baris",
"Cell": "Sel",
"Middle": "Tengah",
"Cell type": "Tipe sel",
"Copy row": "Salin baris",
"Row properties": "Properti baris",
"Table properties": "Properti tabel",
"Bottom": "Bawah",
"V Align": "Rata Atas",
"Header": "Header",
"Right": "Kanan",
"Insert column after": "Sisipkan kolom setelah",
"Cols": "Kolom",
"Insert row after": "Sisipkan baris setelah",
"Width": "Lebar",
"Cell properties": "Properti sel",
"Left": "Kiri",
"Cut row": "Penggal baris",
"Delete column": "Hapus kolom",
"Center": "Tengah",
"Merge cells": "Gabung sel",
"Insert template": "Sisipkan templat",
"Templates": "Templat",
"Background color": "Warna latar belakang",
"Custom...": "Kustom...",
"Custom color": "Warna kustom",
"No color": "Tidak berwarna",
"Text color": "Warna teks",
"Show blocks": "Tampilkan blok",
"Show invisible characters": "Tampilkan karakter tak tampak",
"Words: {0}": "Kata: {0}",
"Insert": "Sisipkan",
"File": "File",
"Edit": "Edit",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area Teks Kaya. Tekan ALT-F9 untuk menu. Tekan ALT-F10 untuk toolbar. Tekan ALT-0 untuk bantuan",
"Tools": "Alat",
"View": "Lihat",
"Table": "Tabel",
"Format": "Format"
});
