/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('it',{
"Cut": "Taglia",
"Heading 5": "Intestazione 5",
"Header 2": "Intestazione 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Il tuo browser non supporta l'accesso diretto agli Appunti. Usa i tasti di scelta rapida Ctrl+X\/C\/V.",
"Heading 4": "Intestazione 4",
"Div": "Div",
"Heading 2": "Intestazione 2",
"Paste": "Incolla",
"Close": "Chiudi",
"Font Family": "Carattere Family",
"Pre": "Pre",
"Align right": "Allinea a destra",
"New document": "Nuovo documento",
"Blockquote": "Blockquote",
"Numbered list": "Elenco numerato",
"Heading 1": "Intestazione 1",
"Headings": "Intestazioni",
"Increase indent": "Aumenta rientro",
"Formats": "Formati",
"Headers": "Intestazioni",
"Select all": "Seleziona tutto",
"Header 3": "Intestazione 3",
"Blocks": "Blocchi",
"Undo": "Annulla",
"Strikethrough": "Barrato",
"Bullet list": "Elenco puntato",
"Header 1": "Intestazione 1",
"Superscript": "Apice",
"Clear formatting": "Cancella formattazione",
"Font Sizes": "Dimensioni carattere",
"Subscript": "Pedice",
"Header 6": "Intestazione 6",
"Redo": "Ripeti",
"Paragraph": "Paragrafo",
"Ok": "Ok",
"Bold": "Grassetto",
"Code": "Codice",
"Italic": "Corsivo",
"Align center": "Allinea al centro",
"Header 5": "Intestazione 5",
"Heading 6": "Intestazione 6",
"Heading 3": "Intestazione 3",
"Decrease indent": "Riduci rientro",
"Header 4": "Intestazione 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Incolla \u00e8 in modalit\u00e0 testo normale. I contenuti sono incollati come testo normale se non disattivi l'opzione.",
"Underline": "Sottolineato",
"Cancel": "Annulla",
"Justify": "Giustifica",
"Inline": "In linea",
"Copy": "Copia",
"Align left": "Allinea a sinistra",
"Visual aids": "Strumenti visivi",
"Lower Greek": "Lower Greek",
"Square": "Square",
"Default": "Predefinito",
"Lower Alpha": "Lower Alpha",
"Circle": "Circle",
"Disc": "Disc",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Nome",
"Anchor": "Ancoraggio",
"You have unsaved changes are you sure you want to navigate away?": "Non hai salvato delle modifiche, vuoi veramente abbandonare la pagina?",
"Restore last draft": "Ripristina ultima bozza",
"Special character": "Carattere speciale",
"Source code": "Codice sorgente",
"B": "B",
"R": "R",
"G": "G",
"Color": "Colore",
"Right to left": "Da destra a sinistra",
"Left to right": "Da sinistra a destra",
"Emoticons": "Faccine",
"Robots": "Robot",
"Document properties": "Propriet\u00e0 documento",
"Title": "Titolo",
"Keywords": "Parole chiave",
"Encoding": "Codifica",
"Description": "Descrizione",
"Author": "Autore",
"Fullscreen": "Schermo intero",
"Horizontal line": "Linea orizzontale",
"Horizontal space": "Spazio orizzontale",
"Insert\/edit image": "Aggiungi\/modifica immagine",
"General": "Generale",
"Advanced": "Avanzate",
"Source": "Origine",
"Border": "Bordo",
"Constrain proportions": "Mantieni proporzioni",
"Vertical space": "Spazio verticale",
"Image description": "Descrizione immagine",
"Style": "Stile",
"Dimensions": "Dimensioni",
"Insert image": "Inserisci immagine",
"Zoom in": "Zoom avanti",
"Contrast": "Contrasto",
"Back": "Indietro",
"Gamma": "Gamma",
"Flip horizontally": "Capovolgi orizzontalmente",
"Resize": "Ridimensiona",
"Sharpen": "Nitidezza",
"Zoom out": "Zoom indietro",
"Image options": "Opzioni immagine",
"Apply": "Applica",
"Brightness": "Luminosit\u00e0",
"Rotate clockwise": "Ruota in senso orario",
"Rotate counterclockwise": "Ruota in senso antiorario",
"Edit image": "Modifica immagine",
"Color levels": "Livelli colore",
"Crop": "Ritaglia",
"Orientation": "Orientamento",
"Flip vertically": "Capovolgi verticalmente",
"Invert": "Inverti",
"Insert date\/time": "Inserisci data\/ora",
"Remove link": "Rimuovi link",
"Url": "Url",
"Text to display": "Testo da visualizzare",
"Anchors": "Chiusure",
"Insert link": "Inserisci link",
"New window": "Nuova finestra",
"None": "Nessuna",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "L'URL inserito sembra essere un link esterno. Vuoi aggiungere il prefisso http:\/\/ richiesto?",
"Target": "Destinazione",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "L'URL inserito sembra essere un indirizzo e-mail. Vuoi aggiungere il prefisso mailto: richiesto?",
"Insert\/edit link": "Aggiungi\/modifica link",
"Insert\/edit video": "Inserisci\/modifica video",
"Poster": "Poster",
"Alternative source": "Sorgente alternativa",
"Paste your embed code below:": "Incolla il codice d'incorporamento qui:",
"Insert video": "Inserisci video",
"Embed": "Incorpora",
"Nonbreaking space": "Spazio unificatore",
"Page break": "Interruzione di pagina",
"Paste as text": "Incolla come testo",
"Preview": "Anteprima",
"Print": "Stampa",
"Save": "Salva",
"Could not find the specified string.": "Impossibile trovare la stringa specificata.",
"Replace": "Sostituisci",
"Next": "Avanti",
"Whole words": "Parole intere",
"Find and replace": "Trova e sostituisci",
"Replace with": "Sostituisci con",
"Find": "Trova",
"Replace all": "Sostituisci tutto",
"Match case": "Maiuscole/minuscole",
"Prev": "Prec",
"Spellcheck": "Controllo ortografico",
"Finish": "Fine",
"Ignore all": "Ignora Tutto",
"Ignore": "Ignora",
"Add to Dictionary": "Aggiungi al dizionario",
"Insert row before": "Inserisci riga sopra",
"Rows": "Righe",
"Height": "Altezza",
"Paste row after": "Incolla riga sotto",
"Alignment": "Allineamento",
"Border color": "Colore bordo",
"Column group": "Gruppo colonne",
"Row": "Riga",
"Insert column before": "Inserisci colonna prima",
"Split cell": "Dividi cella",
"Cell padding": "Riempimento cella",
"Cell spacing": "Spaziatura cella",
"Row type": "Tipo riga",
"Insert table": "Inserisci tabella",
"Body": "Corpo",
"Caption": "Didascalia",
"Footer": "Pi\u00e8 di pagina",
"Delete row": "Elimina riga",
"Paste row before": "Incolla riga sopra",
"Scope": "Ambito",
"Delete table": "Elimina tabella",
"H Align": "Allineamento orizz.",
"Top": "In alto",
"Header cell": "Cella d'intestazione",
"Column": "Colonna",
"Row group": "Gruppo righe",
"Cell": "Cella",
"Middle": "Centrale",
"Cell type": "Tipo di cella",
"Copy row": "Copia riga",
"Row properties": "Propriet\u00e0 riga",
"Table properties": "Propriet\u00e0 tabella",
"Bottom": "In basso",
"V Align": "Allineamento vert.",
"Header": "Intestazione",
"Right": "Destra",
"Insert column after": "Inserisci colonna dopo",
"Cols": "Col",
"Insert row after": "Inserisci riga sotto",
"Width": "Larghezza",
"Cell properties": "Propriet\u00e0 cella",
"Left": "Sinistra",
"Cut row": "Taglia riga",
"Delete column": "Elimina colonna",
"Center": "Centro",
"Merge cells": "Unisci celle",
"Insert template": "Inserisci modello",
"Templates": "Modelli",
"Background color": "Colore sfondo",
"Custom...": "Personalizzato...",
"Custom color": "Colore personalizzato",
"No color": "Nessun colore",
"Text color": "Colore testo",
"Show blocks": "Mostra blocchi",
"Show invisible characters": "Mostra caratteri invisibili",
"Words: {0}": "Parole: {0}",
"Insert": "Inserisci",
"File": "File",
"Edit": "Modifica",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area testo RTF. Premi ALT-F9 per il men\u00f9. Premi ALT-F10 per la barra degli strumenti. Premi ALT-0 per l'aiuto",
"Tools": "Strumenti",
"View": "Visualizza",
"Table": "Tabella",
"Format": "Formato"
});
