/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('ms',{
"Cut": "Potong",
"Heading 5": "Pengepala 5",
"Header 2": "Pengepala 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Pelayar anda tidak menyokong capaian langsung ke papan klip. Sebaliknya sila gunakan Ctrl+X\/C\/V pintasan papan kekunci.",
"Heading 4": "Pengepala 4",
"Div": "Div",
"Heading 2": "Pengepala 2",
"Paste": "Tampal",
"Close": "Tutup",
"Font Family": "Keluarga Fon",
"Pre": "Pre",
"Align right": "Jajar kanan",
"New document": "Dokumen baharu",
"Blockquote": "Tanda petikan tebal",
"Numbered list": "Senarai Bernombor",
"Heading 1": "Pengepala 1",
"Headings": "Pengepala",
"Increase indent": "Tambah Inden",
"Formats": "Format",
"Headers": "Pengepala",
"Select all": "Pilih semua",
"Header 3": "Pengepala 3",
"Blocks": "Blok",
"Undo": "Buat Asal",
"Strikethrough": "Garis lorek",
"Bullet list": "Senarai bulet",
"Header 1": "Pengepala 1",
"Superscript": "Superskrip",
"Clear formatting": "Buang format",
"Font Sizes": "Saiz Fon",
"Subscript": "Subskrip",
"Header 6": "Pengepala 6",
"Redo": "Buat semula",
"Paragraph": "Perenggan",
"Ok": "OK",
"Bold": "Tebal",
"Code": "Kod",
"Italic": "Italik",
"Align center": "Jajar tengah",
"Header 5": "Pengepala 5",
"Heading 6": "Pengepala 6",
"Heading 3": "Pengepala 3",
"Decrease indent": "Kurangkan Inden",
"Header 4": "Pengepala 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Kini tampal berada dalam mod teks biasa. Kandungan kini akan ditampalkan sebagai teks biasa sehingga anda tongol tutupkan pilihan ini.",
"Underline": "Garis bawah",
"Cancel": "Batal",
"Justify": "Imbang",
"Inline": "Sebaris",
"Copy": "Salin",
"Align left": "Jajar kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Huruf Kecil Bahasa Greek",
"Square": "Segiempat tepat",
"Default": "Lalai",
"Lower Alpha": "Huruf Kecil",
"Circle": "Bulatan",
"Disc": "Cakera",
"Upper Alpha": "Huruf Besar",
"Upper Roman": "Huruf Besar Roman",
"Lower Roman": "Huruf Kecil Roman",
"Name": "Nama",
"Anchor": "Sauh",
"You have unsaved changes are you sure you want to navigate away?": "Anda mempunyai perubahan yang belum disimpan, adakah anda pasti anda ingin menavigasi keluar?",
"Restore last draft": "Pulihkan draf terakhir",
"Special character": "Aksara khas",
"Source code": "Kod sumber",
"B": "B",
"R": "R",
"G": "G",
"Color": "Warna",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Sifat dokumen",
"Title": "Tajuk",
"Keywords": "Kata kunci",
"Encoding": "Pengekodan",
"Description": "Keterangan",
"Author": "Pengarang",
"Fullscreen": "Skrin penuh",
"Horizontal line": "Garis mendatar",
"Horizontal space": "Ruang mendatar",
"Insert\/edit image": "Sisipkan\/imej edit",
"General": "Umum",
"Advanced": "Lanjutan",
"Source": "Sumber",
"Border": "Sempadan",
"Constrain proportions": "Perkadaran had",
"Vertical space": "Ruang menegak",
"Image description": "Keterangan imej",
"Style": "Gaya",
"Dimensions": "Dimensi",
"Insert image": "Sisipkan Imej",
"Zoom in": "Zum masuk",
"Contrast": "Kontras",
"Back": "Kembali",
"Gamma": "Gamma",
"Flip horizontally": "Balikkan secara mendatar",
"Resize": "Saiz Semula",
"Sharpen": "Tajamkan",
"Zoom out": "Zum Keluar",
"Image options": "Pilihan imej",
"Apply": "Gunakan",
"Brightness": "Kecerahan",
"Rotate clockwise": "Putar ikut arah jam",
"Rotate counterclockwise": "Putar ikut lawan arah jam",
"Edit image": "Edit imej",
"Color levels": "Tahap warna",
"Crop": "Pangkas",
"Orientation": "Orientasi",
"Flip vertically": "Balikkan secara menegak",
"Invert": "Songsang",
"Insert date\/time": "Sisipkan tarikh\/masa",
"Remove link": "Alih keluar pautan",
"Url": "Url",
"Text to display": "Teks untuk dipaparkan",
"Anchors": "Sauh",
"Insert link": "Sisipkan pautan",
"New window": "Tetingkap baharu",
"None": "Tiada",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL yang anda masukkan kelihatan seperti pautan luaran. Adakah anda ingin menambah awalan http:\/\/ yang diperlukan?",
"Target": "Sasaran",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL yang anda masukkan kelihatan seperti alamat e-mel. Adakah anda ingin menambah awalan mailto: yang diperlukan?",
"Insert\/edit link": "Sisipkan\/pautan edit",
"Insert\/edit video": "Sisipkan\/video edit",
"Poster": "Poster",
"Alternative source": "Sumber alternatif",
"Paste your embed code below:": "Tampalkan kod terbenam anda di bawah:",
"Insert video": "Sisipkan video",
"Embed": "Benam",
"Nonbreaking space": "Ruang bukan pemisah",
"Page break": "Pemisah halaman",
"Paste as text": "Tampalkan sebagai teks",
"Preview": "Pratonton",
"Print": "Cetak",
"Save": "Simpan",
"Could not find the specified string.": "Tidak dapat menemui rentetan yang ditentukan.",
"Replace": "Ganti",
"Next": "Seterusnya",
"Whole words": "Seluruh kata",
"Find and replace": "Cari dan ganti",
"Replace with": "Ganti dengan",
"Find": "Cari",
"Replace all": "Ganti semua",
"Match case": "Padanan huruf",
"Prev": "Sebelumnya",
"Spellcheck": "Semak ejaan",
"Finish": "Selesai",
"Ignore all": "Abaikan semua",
"Ignore": "Abai",
"Add to Dictionary": "Tambah ke Kamus",
"Insert row before": "Sisipkan lajur sebelum",
"Rows": "Baris",
"Height": "Tinggi",
"Paste row after": "Tampal baris selepas",
"Alignment": "Penjajaran",
"Border color": "Warna sempadan",
"Column group": "Kumpulan lajur",
"Row": "Baris",
"Insert column before": "Sisipkan lajur sebelum",
"Split cell": "Pecahkan sel",
"Cell padding": "Pad sel",
"Cell spacing": "Jarak sel",
"Row type": "Jenis baris",
"Insert table": "Sisipkan jadual",
"Body": "Isi",
"Caption": "Kapsyen",
"Footer": "Pengaki",
"Delete row": "Padam baris",
"Paste row before": "Tampal baris sebelum",
"Scope": "Skop",
"Delete table": "Padam jadual",
"H Align": "Jajar H",
"Top": "Atas",
"Header cell": "Pengepala sel",
"Column": "Lajur",
"Row group": "Kumpulan baris",
"Cell": "Sel",
"Middle": "Tengah",
"Cell type": "Jenis sel",
"Copy row": "Salin baris",
"Row properties": "Sifat baris",
"Table properties": "Sifat jadual",
"Bottom": "Bawah",
"V Align": "Jajar V",
"Header": "Pengepala",
"Right": "Kanan",
"Insert column after": "Sisipkan lajur selepas",
"Cols": "Lajur",
"Insert row after": "Sisipkan lajur selepas",
"Width": "Lebar",
"Cell properties": "Sifat sel",
"Left": "Kiri",
"Cut row": "Potong baris",
"Delete column": "Padam lajur",
"Center": "Tengah",
"Merge cells": "Cantum sel",
"Insert template": "Sisipkan templat",
"Templates": "Templat",
"Background color": "Warna latar",
"Custom...": "Tersuai...",
"Custom color": "Warna tersuai",
"No color": "Tiada warna",
"Text color": "Warna teks",
"Show blocks": "Tunjuk blok",
"Show invisible characters": "Tunjuk aksara halimunan",
"Words: {0}": "Kata: {0}",
"Insert": "Sisip",
"File": "Fail",
"Edit": "Edit",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Kawasan Teks Beraneka. Tekan ALT-F9 untuk menu. Tekan ALT-F10 untuk bar alat. Tekan ALT-0 untuk bantuan",
"Tools": "Alatan",
"View": "Lihat",
"Table": "Jadual",
"Format": "Format"
});
