/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n("nl",{
"Cut": "Knippen",
"Heading 5": "Kop 5",
"Header 2": "Koptekst 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Je browser biedt geen ondersteuning voor rechtstreekse toegang tot het klembord. Gebruik in plaats daarvan de sneltoetsen Ctrl+X\/C\/V.",
"Heading 4": "Kop 4",
"Div": "Div",
"Heading 2": "Kop 2",
"Paste": "Plakken",
"Close": "Sluiten",
"Font Family": "Lettertypefamilie",
"Pre": "Pre",
"Align right": "Tekst rechts uitlijnen",
"New document": "Nieuw document",
"Blockquote": "Quote",
"Numbered list": "Genummerde lijst",
"Heading 1": "Kop 1",
"Headings": "Koppen",
"Increase indent": "Inspringing vergroten",
"Formats": "Opmaak",
"Headers": "Kopteksten",
"Select all": "Alle zichtbare items selecteren",
"Header 3": "Koptekst 3",
"Blocks": "Blokken",
"Undo": "Ongedaan maken",
"Strikethrough": "Lijn trekken door het midden van de tekst",
"Bullet list": "Lijst met opsommingstekens",
"Header 1": "Koptekst 1",
"Superscript": "Superscript",
"Clear formatting": "Opmaak verwijderen",
"Font Sizes": "Tekengrootte",
"Subscript": "Subscript",
"Header 6": "Koptekst 6",
"Redo": "Opnieuw",
"Paragraph": "Alinea",
"Ok": "OK",
"Bold": "Tekst vet maken",
"Code": "Code",
"Italic": "Cursief",
"Align center": "Tekst midden uitlijnen",
"Header 5": "Koptekst 5",
"Heading 6": "Kop 6",
"Heading 3": "Kop 3",
"Decrease indent": "Inspringing verkleinen",
"Header 4": "Koptekst 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Plakken gebeurt nu als platte tekst. Tekst wordt nu ingevoegd zonder opmaak tot deze optie wordt uitgeschakeld.",
"Underline": "Tekst onderstrepen",
"Cancel": "Annuleren",
"Justify": "Uitvullen",
"Inline": "In bericht",
"Copy": "Kopi\u00ebren",
"Align left": "Tekst links uitlijnen",
"Visual aids": "Visuele hulpmiddelen",
"Lower Greek": "Kleine Griekse letter",
"Square": "Vierkant",
"Default": "Standaard",
"Lower Alpha": "Kleine alpa letter",
"Circle": "Cirkel",
"Disc": "Schijf",
"Upper Alpha": "Alpha hoofdletter",
"Upper Roman": "Rechte hoofdletter",
"Lower Roman": "Klein rechte letter",
"Name": "Naam",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Er zijn onopgeslagen wijzigingen. Weet je zeker dat je de pagina wilt verlaten?",
"Restore last draft": "Laatste concept herstellen",
"Special character": "Speciale tekens",
"Source code": "Broncode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Kleur",
"Right to left": "Van rechts naar links",
"Left to right": "Van links naar rechts",
"Emoticons": "Emoticons",
"Robots": "Robots",
"Document properties": "Documenteigenschappen",
"Title": "Titel",
"Keywords": "Sleutelwoorden",
"Encoding": "Codering",
"Description": "Omschrijving",
"Author": "Auteur",
"Fullscreen": "Volledig scherm",
"Horizontal line": "Horizontale lijn",
"Horizontal space": "Horizontale ruimte",
"Insert\/edit image": "Afbeelding invoegen\/bewerken",
"General": "Algemeen",
"Advanced": "Geavanceerd",
"Source": "Bron",
"Border": "Rand",
"Constrain proportions": "Verhoudingen behouden",
"Vertical space": "Verticale ruimte",
"Image description": "Afbeeldingsbeschrijving",
"Style": "Stijl",
"Dimensions": "Afmetingen",
"Insert image": "Afbeelding invoegen",
"Zoom in": "Inzoomen",
"Contrast": "Contrast",
"Back": "Vorige",
"Gamma": "Gamma",
"Flip horizontally": "Horizontaal spiegelen",
"Resize": "Formaat aanpassen",
"Sharpen": "Verscherpen",
"Zoom out": "Uitzoomen",
"Image options": "Afbeeldingsopties",
"Apply": "Toepassen",
"Brightness": "Helderheid",
"Rotate clockwise": "Rechtsom draaien",
"Rotate counterclockwise": "Linksom draaien",
"Edit image": "Afbeelding bewerken",
"Color levels": "Kleurniveaus",
"Crop": "Bijsnijden",
"Orientation": "Afdrukstand",
"Flip vertically": "Verticaal spiegelen",
"Invert": "Omkeren",
"Insert date\/time": "Datum\/tijd invoegen",
"Remove link": "Link verwijderen",
"Url": "Url",
"Text to display": "Weer te geven tekst",
"Anchors": "Anker",
"Insert link": "Hyperlink invoegen",
"New window": "Nieuw venster",
"None": "Geen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "De opgegeven URL is een externe link. Wil je het vereiste voorvoegsel http:\/\/ toevoegen?",
"Target": "Doel",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "De opgegeven URL is een e-mailadres. Wil je het vereiste voorvoegsel mailto: toevoegen?",
"Insert\/edit link": "Link invoegen\/bewerken",
"Insert\/edit video": "Video invoegen\/bewerken",
"Poster": "Poster",
"Alternative source": "Alternatieve bron",
"Paste your embed code below:": "Plak de insluitingscode hieronder:",
"Insert video": "Video invoegen",
"Embed": "Insluiten",
"Nonbreaking space": "Vaste spatie",
"Page break": "Pagina-einde",
"Paste as text": "Plakken als tekst",
"Preview": "Bekijken",
"Print": "Afdrukken",
"Save": "Opslaan",
"Could not find the specified string.": "Kan de opgeven tekenreeks niet vinden.",
"Replace": "Vervangen",
"Next": "Volgende",
"Whole words": "Hele woorden",
"Find and replace": "Zoeken en vervangen",
"Replace with": "Vervangen door",
"Find": "Zoeken",
"Replace all": "Alles vervangen",
"Match case": "Identieke hoofdletters/kleine letters",
"Prev": "Vorig",
"Spellcheck": "Spellingcontrole",
"Finish": "Voltooien",
"Ignore all": "Alles negeren",
"Ignore": "Negeren",
"Add to Dictionary": "Aan woordenboek toevoegen",
"Insert row before": "Rij toevoegen voor",
"Rows": "Rijen",
"Height": "Hoogte",
"Paste row after": "Rij plakken na",
"Alignment": "Uitlijning",
"Border color": "Randkleur",
"Column group": "Kolomgroep",
"Row": "Rij",
"Insert column before": "Kolom invoegen voor",
"Split cell": "Cel splitsen",
"Cell padding": "Celopvulling",
"Cell spacing": "Celafstand",
"Row type": "Rijtype",
"Insert table": "Tabel invoegen",
"Body": "Berichtinhoud",
"Caption": "Bijschrift",
"Footer": "Voettekst",
"Delete row": "Rij verwijderen",
"Paste row before": "Rij plakken voor",
"Scope": "Bereik",
"Delete table": "Tabel verwijderen",
"H Align": "H uitlijnen",
"Top": "Bovenaan",
"Header cell": "Koptekstcel",
"Column": "Kolom",
"Row group": "Rijgroep",
"Cell": "Cel",
"Middle": "Tussenvoegsel",
"Cell type": "Celtype",
"Copy row": "Rij kopi\u00ebren",
"Row properties": "Rij-eigenschappen",
"Table properties": "Tabeleigenschappen",
"Bottom": "Onderaan",
"V Align": "V uitlijnen",
"Header": "Koptekst",
"Right": "Rechts",
"Insert column after": "Kolom invoegen na",
"Cols": "Kolommen",
"Insert row after": "Rij invoegen na",
"Width": "Breedte",
"Cell properties": "Celeigenschappen",
"Left": "Links",
"Cut row": "Rij knippen",
"Delete column": "Kolom verwijderen",
"Center": "Centreren",
"Merge cells": "Cellen samenvoegen",
"Insert template": "Sjabloon invoegen",
"Templates": "Sjablonen",
"Background color": "Achtergrondkleur",
"Custom...": "Aangepast...",
"Custom color": "Aangepaste kleur",
"No color": "Geen kleur",
"Text color": "Tekstkleur",
"Show blocks": "Blokken tonen",
"Show invisible characters": "Onzichtbare tekens tonen",
"Words: {0}": "Woorden: {0}",
"Insert": "Invoegen",
"File": "Bestand",
"Edit": "Bewerken",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Gebied met opgemaakte tekst. Druk op ALT-F9 om het menu weer te geven. Druk op ALT-F10 om de werkbalk weer te geven. Druk op ALT-0 om Help weer te geven.",
"Tools": "Hulpmiddelen",
"View": "Weergeven",
"Table": "Tabel",
"Format": "Opmaak"
});
