/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('nb-NO',{
"Cut": "Klipp ut",
"Heading 5": "Topptekst 5",
"Header 2": "Topptekst 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Nettleseren din st\u00f8tter ikke direkte tilgang til utklippstavlen. Bruk hurtigtastene Ctrl+X\/C\/V i stedet.",
"Heading 4": "Topptekst 4",
"Div": "Div",
"Heading 2": "Topptekst 2",
"Paste": "Lim inn",
"Close": "Lukk",
"Font Family": "Skrifttype",
"Pre": "Pre",
"Align right": "H\u00f8yrejuster",
"New document": "Nytt dokument",
"Blockquote": "Sitatblokk",
"Numbered list": "Nummerert liste",
"Heading 1": "Topptekst 1",
"Headings": "Overskrifter",
"Increase indent": "\u00d8k innrykk",
"Formats": "Formater",
"Headers": "Topptekster",
"Select all": "Merk alt",
"Header 3": "Topptekst 3",
"Blocks": "Blokker",
"Undo": "Angre",
"Strikethrough": "Gjennomstreket",
"Bullet list": "Punktliste",
"Header 1": "Topptekst 1",
"Superscript": "Hevet",
"Clear formatting": "Fjern formatering",
"Font Sizes": "Skriftst\u00f8rrelser",
"Subscript": "Senket",
"Header 6": "Topptekst 6",
"Redo": "Gj\u00f8r om",
"Paragraph": "Avsnitt",
"Ok": "OK",
"Bold": "Fet",
"Code": "Kode",
"Italic": "Kursiv",
"Align center": "Midtstilt",
"Header 5": "Topptekst 5",
"Heading 6": "Topptekst 6",
"Heading 3": "Topptekst 3",
"Decrease indent": "Reduser innrykk",
"Header 4": "Topptekst 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Lim inn er n\u00e5 i ren tekstmodus. Innhold blir limt inn som ren tekst til du bytter modus.",
"Underline": "Understreking",
"Cancel": "Avbryt",
"Justify": "Blokkjuster",
"Inline": "Linjebundet",
"Copy": "Kopier",
"Align left": "Venstrejustert",
"Visual aids": "Visuelle hjelpemidler",
"Lower Greek": "Sm\u00e5 greske",
"Square": "Firkant",
"Default": "Standard",
"Lower Alpha": "Sm\u00e5 bokstaver",
"Circle": "Sirkel",
"Disc": "Punkttegn",
"Upper Alpha": "Store bokstaver",
"Upper Roman": "Store romertall",
"Lower Roman": "Sm\u00e5 romertall",
"Name": "Navn",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Du har endringer som ikke er lagret. Er du sikker p\u00e5 at du vil navigere bort?",
"Restore last draft": "Gjenopprett siste utkast",
"Special character": "Spesialtegn",
"Source code": "Kildekode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Farge",
"Right to left": "H\u00f8yre mot venstre",
"Left to right": "Venstre mot h\u00f8yre",
"Emoticons": "Uttrykksikoner",
"Robots": "Roboter",
"Document properties": "Dokumentegenskaper",
"Title": "Tittel",
"Keywords": "N\u00f8kkelord",
"Encoding": "Koding",
"Description": "Beskrivelse",
"Author": "Forfatter",
"Fullscreen": "Fullskjerm",
"Horizontal line": "Vannrett linje",
"Horizontal space": "Vannrett avstand",
"Insert\/edit image": "Sett inn \/ rediger bilde",
"General": "Generelt",
"Advanced": "Avansert",
"Source": "Kilde",
"Border": "Kantlinje",
"Constrain proportions": "Behold proporsjoner",
"Vertical space": "Loddrett avstand",
"Image description": "Bildebeskrivelse",
"Style": "Stil",
"Dimensions": "M\u00e5l",
"Insert image": "Sett inn bilde",
"Zoom in": "Zoom inn",
"Contrast": "Kontrast",
"Back": "Tilbake",
"Gamma": "Gamma",
"Flip horizontally": "Vend vannrett",
"Resize": "Endre st\u00f8rrelse",
"Sharpen": "Gj\u00f8r skarpere",
"Zoom out": "Zoom ut",
"Image options": "Bildealternativer",
"Apply": "Bruk",
"Brightness": "Lysstyrke",
"Rotate clockwise": "Roter med klokken",
"Rotate counterclockwise": "Roter mot klokken",
"Edit image": "Rediger bilde",
"Color levels": "Fargeniv\u00e5er",
"Crop": "Beskj\u00e6r",
"Orientation": "Retning",
"Flip vertically": "Vend loddrett",
"Invert": "Inverter",
"Insert date\/time": "Sett inn dato\/klokkeslett",
"Remove link": "Fjern kobling",
"Url": "URL-adresse",
"Text to display": "Tekst som skal vises",
"Anchors": "Ankre",
"Insert link": "Sett inn kobling",
"New window": "Nytt vindu",
"None": "Ingen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Den angitte URL-adressen ser ut til \u00e5 v\u00e6re en ekstern kobling. Vil du legge til det n\u00f8dvendige http:\/\/-prefikset?",
"Target": "M\u00e5l",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Den angitte URL-adressen ser ut til \u00e5 v\u00e6re en e-postadresse. Vil du legge til det n\u00f8dvendige mailto:-prefikset?",
"Insert\/edit link": "Sett inn \/ rediger kobling",
"Insert\/edit video": "Sett inn \/ rediger video",
"Poster": "Plakat",
"Alternative source": "Alternativ kilde",
"Paste your embed code below:": "Lim inn innebyggingskoden nedenfor:",
"Insert video": "Sett inn video",
"Embed": "Bygg inn",
"Nonbreaking space": "Hardt mellomrom",
"Page break": "Sideskift",
"Paste as text": "Lim inn som tekst",
"Preview": "Forh\u00e5ndsvis",
"Print": "Skriv ut",
"Save": "Lagre",
"Could not find the specified string.": "Finner ikke den angitte strengen.",
"Replace": "Erstatt",
"Next": "Neste",
"Whole words": "Hele ord",
"Find and replace": "S\u00f8k og erstatt",
"Replace with": "Erstatt med",
"Find": "Finn",
"Replace all": "Erstatt alle",
"Match case": "Skill mellom store og sm\u00e5 bokstaver",
"Prev": "Forrige",
"Spellcheck": "Stavekontroll",
"Finish": "Fullf\u00f8r",
"Ignore all": "Ignorer alle",
"Ignore": "Ignorer",
"Add to Dictionary": "Legg til i ordliste",
"Insert row before": "Sett inn rad foran",
"Rows": "Rader",
"Height": "H\u00f8yde",
"Paste row after": "Lim inn rad etter",
"Alignment": "Justering",
"Border color": "Kantlinjefarge",
"Column group": "Kolonnegruppe",
"Row": "Rad",
"Insert column before": "Sett inn kolonne foran",
"Split cell": "Del celle",
"Cell padding": "Celleutfylling",
"Cell spacing": "Celleavstand",
"Row type": "Radtype",
"Insert table": "Sett inn tabell",
"Body": "Br\u00f8dtekst",
"Caption": "Bildetekst",
"Footer": "Bunntekst",
"Delete row": "Slett rad",
"Paste row before": "Lim inn rad foran",
"Scope": "Omr\u00e5de",
"Delete table": "Slett tabell",
"H Align": "Vannrett justering",
"Top": "Topp",
"Header cell": "Topptekstcelle",
"Column": "Kolonne",
"Row group": "Radgruppe",
"Cell": "Celle",
"Middle": "Midten",
"Cell type": "Celletype",
"Copy row": "Kopier rad",
"Row properties": "Radegenskaper",
"Table properties": "Tabellegenskaper",
"Bottom": "Bunn",
"V Align": "Loddrett justering",
"Header": "Topptekst",
"Right": "H\u00f8yre",
"Insert column after": "Sett inn kolonne etter",
"Cols": "Kolonner",
"Insert row after": "Sett inn rad etter",
"Width": "Bredde",
"Cell properties": "Celleegenskaper",
"Left": "Venstre",
"Cut row": "Klipp ut rad",
"Delete column": "Slett kolonne",
"Center": "Midtstilt",
"Merge cells": "Sl\u00e5 sammen celler",
"Insert template": "Sett inn mal",
"Templates": "Maler",
"Background color": "Bakgrunnsfarge",
"Custom...": "Egendefinert...",
"Custom color": "Egendefinert farge",
"No color": "Ingen farge",
"Text color": "Tekstfarge",
"Show blocks": "Vis blokker",
"Show invisible characters": "Vis usynlige tegn",
"Words: {0}": "Ord: {0}",
"Insert": "Sett inn",
"File": "Fil",
"Edit": "Rediger",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rik tekst-omr\u00e5de. Trykk p\u00e5 ALT+F9 for meny. Trykk p\u00e5 ALT+F10 for verkt\u00f8ylinje. Trykk p\u00e5 ALT+0 for hjelp",
"Tools": "Verkt\u00f8y",
"View": "Vis",
"Table": "Tabell",
"Format": "Format",
});

