/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('pt_PT',{
"Cut": "Cortar",
"Heading 5": "T\u00edtulo n.\u00ba 5",
"Header 2": "Cabe\u00e7alho n.\u00ba 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "O seu navegador n\u00e3o \u00e9 compat\u00edvel com o acesso direto \u00e0 \u00e1rea de transfer\u00eancia. Utilize antes os atalhos Ctrl+X\/C\/V do teclado.",
"Heading 4": "T\u00edtulo n.\u00ba 4",
"Div": "Div",
"Heading 2": "T\u00edtulo n.\u00ba 2",
"Paste": "Colar",
"Close": "Fechar",
"Font Family": "Fam\u00edlia do tipo de letra",
"Pre": "Pre",
"Align right": "Alinhar \u00e0 direita",
"New document": "Novo documento",
"Blockquote": "Cita\u00e7\u00e3o em bloco",
"Numbered list": "Lista numerada",
"Heading 1": "T\u00edtulo n.\u00ba 1",
"Headings": "T\u00edtulos",
"Increase indent": "Aumentar avan\u00e7o",
"Formats": "Formatos",
"Headers": "Cabe\u00e7alhos",
"Select all": "Selecionar tudo",
"Header 3": "Cabe\u00e7alho n.\u00ba 3",
"Blocks": "Blocos",
"Undo": "Anular",
"Strikethrough": "Rasurar",
"Bullet list": "Lista com marcas",
"Header 1": "Cabe\u00e7alho n.\u00ba 1",
"Superscript": "Superior \u00e0 linha",
"Clear formatting": "Limpar formata\u00e7\u00e3o",
"Font Sizes": "Tamanhos do tipo de letra",
"Subscript": "Inferior \u00e0 linha",
"Header 6": "Cabe\u00e7alho n.\u00ba 6",
"Redo": "Refazer",
"Paragraph": "Par\u00e1grafo",
"Ok": "Ok",
"Bold": "Negrito",
"Code": "C\u00f3digo",
"Italic": "It\u00e1lico",
"Align center": "Alinhar ao centro",
"Header 5": "Cabe\u00e7alho n.\u00ba 5",
"Heading 6": "T\u00edtulo n.\u00ba 6",
"Heading 3": "T\u00edtulo n.\u00ba 3",
"Decrease indent": "Diminuir avan\u00e7o",
"Header 4": "Cabe\u00e7alho n.\u00ba 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "O comando "colar" est\u00e1 agora no modo de texto simples. O conte\u00fado ser\u00e1 agora colado como texto simples at\u00e9 desativar esta op\u00e7\u00e3o.",
"Underline": "Sublinhar",
"Cancel": "Cancelar",
"Justify": "Justificar",
"Inline": "No texto",
"Copy": "Copiar",
"Align left": "Alinhar \u00e0 esquerda",
"Visual aids": "Ajuda visual",
"Lower Greek": "\\u03b1.,\\u03b2.,\\u03b3., etc.",
"Square": "Quadrado",
"Default": "Predefini\u00e7\u00e3o",
"Lower Alpha": "a., b., c., etc.",
"Circle": "C\u00edrculo",
"Disc": "Disco",
"Upper Alpha": "A., B., C., etc.",
"Upper Roman": "I., II., III., etc.",
"Lower Roman": "i., ii., iii., etc.",
"Name": "Nome",
"Anchor": "\u00c2ncora",
"You have unsaved changes are you sure you want to navigate away?": "Existem altera\u00e7\u00f5es que ainda n\u00e3o foram guardadas. Tem a certeza de que pretende sair?",
"Restore last draft": "Restaurar \u00faltimo rascunho",
"Special character": "Car\u00e1cter especial",
"Source code": "C\u00f3digo-fonte",
"B": "B",
"R": "R",
"G": "G",
"Color": "Cor",
"Right to left": "Da direita para a esquerda",
"Left to right": "Da esquerda para a direita",
"Emoticons": "\u00cdcones expressivos",
"Robots": "Rob\u00f4s",
"Document properties": "Propriedades do documento",
"Title": "T\u00edtulo",
"Keywords": "Palavras-chave",
"Encoding": "Codifica\u00e7\u00e3o",
"Description": "Descri\u00e7\u00e3o",
"Author": "Autor",
"Fullscreen": "Ecr\u00e3 inteiro",
"Horizontal line": "Linha horizontal",
"Horizontal space": "Espa\u00e7amento horizontal",
"Insert\/edit image": "Inserir\/editar imagem",
"General": "Geral",
"Advanced": "Avan\u00e7ado",
"Source": "Origem",
"Border": "Limite",
"Constrain proportions": "Manter propor\u00e7\u00f5es",
"Vertical space": "Espa\u00e7amento vertical",
"Image description": "Descri\u00e7\u00e3o da imagem",
"Style": "Estilo",
"Dimensions": "Dimens\u00f5es",
"Insert image": "Inserir imagem",
"Zoom in": "Aproximar",
"Contrast": "Contraste",
"Back": "Retroceder",
"Gamma": "Gama",
"Flip horizontally": "Inverter horizontalmente",
"Resize": "Redimensionar",
"Sharpen": "Aperfei\u00e7oar",
"Zoom out": "Afastar",
"Image options": "Op\u00e7\u00f5es de imagem",
"Apply": "Aplicar",
"Brightness": "Brilho",
"Rotate clockwise": "Rodar para a direita",
"Rotate counterclockwise": "Rodar para a esquerda",
"Edit image": "Editar imagem",
"Color levels": "N\u00edveis de cor",
"Crop": "Recortar",
"Orientation": "Orienta\u00e7\u00e3o",
"Flip vertically": "Inverter verticalmente",
"Invert": "Inverter",
"Insert date\/time": "Inserir data\/hora",
"Remove link": "Remover liga\u00e7\u00e3o",
"Url": "URL",
"Text to display": "Texto a apresentar",
"Anchors": "\u00c2ncoras",
"Insert link": "Inserir liga\u00e7\u00e3o",
"New window": "Nova janela",
"None": "Nenhum",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "O URL que introduziu parece ser uma liga\u00e7\u00e3o externa. Pretende adicionar o prefixo http:\/\/ necess\u00e1rio?",
"Target": "Destino",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "O URL que introduziu parece ser um endere\u00e7o de email. Pretende adicionar o prefixo mailto: necess\u00e1rio?",
"Insert\/edit link": "Inserir\/editar liga\u00e7\u00e3o",
"Insert\/edit video": "Inserir\/editar v\u00eddeo",
"Poster": "Publicador",
"Alternative source": "Origem alternativa",
"Paste your embed code below:": "Cole o c\u00f3digo para incorporar abaixo:",
"Insert video": "Inserir v\u00eddeo",
"Embed": "Incorporar",
"Nonbreaking space": "Espa\u00e7o fixo",
"Page break": "Quebra de p\u00e1gina",
"Paste as text": "Colar como texto",
"Preview": "Pr\u00e9-visualizar",
"Print": "Imprimir",
"Save": "Guardar",
"Could not find the specified string.": "N\u00e3o foi poss\u00edvel localizar a cadeia especificada.",
"Replace": "Substituir",
"Next": "Seguinte",
"Whole words": "Palavras completas",
"Find and replace": "Localizar e substituir",
"Replace with": "Substituir por",
"Find": "Encontrar",
"Replace all": "Substituir tudo",
"Match case": "Diferenciar mai\u00fasculas e min\u00fasculas",
"Prev": "Anterior",
"Spellcheck": "Verificar ortografia",
"Finish": "Concluir",
"Ignore all": "Ignorar tudo",
"Ignore": "Ignorar",
"Add to Dictionary": "Adicionar ao dicion\u00e1rio",
"Insert row before": "Inserir linha antes",
"Rows": "Linhas",
"Height": "Altura",
"Paste row after": "Colar linha depois",
"Alignment": "Alinhamento",
"Border color": "Cor do limite",
"Column group": "Grupo de colunas",
"Row": "Linha",
"Insert column before": "Inserir coluna antes",
"Split cell": "Dividir c\u00e9lula",
"Cell padding": "Espa\u00e7amento interno da c\u00e9lula",
"Cell spacing": "Espa\u00e7amento entre c\u00e9lulas",
"Row type": "Tipo de linha",
"Insert table": "Inserir tabela",
"Body": "Corpo",
"Caption": "Legenda",
"Footer": "Rodap\u00e9",
"Delete row": "Eliminar linha",
"Paste row before": "Colar linha antes",
"Scope": "\u00c2mbito",
"Delete table": "Eliminar tabela",
"H Align": "Alinhamento h.",
"Top": "Topo",
"Header cell": "C\u00e9lula de cabe\u00e7alho",
"Column": "Coluna",
"Row group": "Grupo de linhas",
"Cell": "C\u00e9lula",
"Middle": "Meio",
"Cell type": "Tipo de c\u00e9lula",
"Copy row": "Copiar linha",
"Row properties": "Propriedades da linha",
"Table properties": "Propriedades da tabela",
"Bottom": "Fundo",
"V Align": "Alinhamento v.",
"Header": "Cabe\u00e7alho",
"Right": "Direita",
"Insert column after": "Inserir coluna depois",
"Cols": "Colunas",
"Insert row after": "Inserir linha depois",
"Width": "Largura",
"Cell properties": "Propriedades da c\u00e9lula",
"Left": "Esquerda",
"Cut row": "Cortar linha",
"Delete column": "Eliminar coluna",
"Center": "Centrar",
"Merge cells": "Unir c\u00e9lulas",
"Insert template": "Inserir modelo",
"Templates": "Modelos",
"Background color": "Cor de fundo",
"Custom...": "Personalizado...",
"Custom color": "Cor personalizada",
"No color": "Nenhuma cor",
"Text color": "Cor do texto",
"Show blocks": "Mostrar blocos",
"Show invisible characters": "Mostrar caracteres invis\u00edveis",
"Words: {0}": "Palavras: {0}",
"Insert": "Inserir",
"File": "Ficheiro",
"Edit": "Editar",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "\u00c1rea de texto formatado. Prima ALT-F9 para visualizar o menu. Prima ALT-F10 para visualizar a barra de ferramentas. Prima ALT-0 para visualizar a ajuda",
"Tools": "Ferramentas",
"View": "Visualizar",
"Table": "Tabela",
"Format": "Formato",
});
