/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014 Zimbra, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: http://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.
 * All portions of the code are Copyright (C) 2014 Zimbra, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('ro',{
"Cut": "Decupare",
"Heading 5": "Titlu 5",
"Header 2": "Antet 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browserul dumneavoastr\u0103 nu support\u0103 acces direct la clipboard. Folosi\u0163i combina\u0163ile de tastatur\u0103 Ctrl+X\/C\/V.",
"Heading 4": "Titlu 4",
"Div": "Div",
"Heading 2": "Titlu 2",
"Paste": "Lipire",
"Close": "\u00cenchidere",
"Font Family": "Familie font",
"Pre": "Pre",
"Align right": "Aliniere la dreapta",
"New document": "Document nou",
"Blockquote": "Men\u0163iune bloc",
"Numbered list": "List\u0103 ordonat\u0103",
"Heading 1": "Titlu 1",
"Headings": "Titluri",
"Increase indent": "Indenteaz\u0103",
"Formats": "Formate",
"Headers": "Antete",
"Select all": "Selectare toate",
"Header 3": "Antet 3",
"Blocks": "Blocuri",
"Undo": "Anulare",
"Strikethrough": "T\u0103iere",
"Bullet list": "List\u0103 neordonat\u0103",
"Header 1": "Antet 1",
"Superscript": "Exponent",
"Clear formatting": "\u015eterge format\u0103rile",
"Font Sizes": "Dimensiune font",
"Subscript": "Indice",
"Header 6": "Antet 6",
"Redo": "Dezexecut\u0103",
"Paragraph": "Paragraf",
"Ok": "Ok",
"Bold": "Aldin",
"Code": "Cod",
"Italic": "Italic",
"Align center": "Aliniere la centru",
"Header 5": "Antet 5",
"Heading 6": "Titlu 6",
"Heading 3": "Titlu 3",
"Decrease indent": "De-indenteaz\u0103",
"Header 4": "Antet 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Functia lipe\u015fte este acum \u00een modul text simplu. Continutul va fi acum inserat ca text simplu p\u00e2n\u0103 c\u00e2nd aceast\u0103 op\u021biune va fi dezactivat\u0103.",
"Underline": "Subliniere",
"Cancel": "Anulare",
"Justify": "Aliniere pe toat\u0103 l\u0103\u021bimea",
"Inline": "Inline",
"Copy": "Copiere",
"Align left": "Aliniere la st\u00e2nga",
"Visual aids": "Ajutor vizual",
"Lower Greek": "Minuscule Grecesti",
"Square": "P\u0103trat",
"Default": "Implicit",
"Lower Alpha": "Minuscule Alfanumerice",
"Circle": "Cerc",
"Disc": "Disc",
"Upper Alpha": "Majuscule Alfanumerice",
"Upper Roman": "Majuscule Romane",
"Lower Roman": "Minuscule Romane",
"Name": "Nume",
"Anchor": "Ancor\u0103",
"You have unsaved changes are you sure you want to navigate away?": "Ave\u021bi modific\u0103ri nesalvate!Sigur dori\u0163i s\u0103 ie\u015fiti?",
"Restore last draft": "Restaurare la ultima salvare",
"Special character": "Caractere speciale",
"Source code": "Codul surs\u0103",
"B": "B",
"R": "R",
"G": "G",
"Color": "Culoare",
"Right to left": "De la dreapta la st\u00e2nga",
"Left to right": "De la st\u00e2nga la dreapta",
"Emoticons": "Emoticonuri",
"Robots": "Robo\u021bi",
"Document properties": "Propriet\u0103\u021bi document",
"Title": "Titlu",
"Keywords": "Cuvinte cheie",
"Encoding": "Codare",
"Description": "Descriere",
"Author": "Autor",
"Fullscreen": "Ecran complet",
"Horizontal line": "Linie orizontal\u0103",
"Horizontal space": "Spa\u021biu orizontal",
"Insert\/edit image": "Inserare\/editare imagini",
"General": "General",
"Advanced": "Avansat",
"Source": "Surs\u0103",
"Border": "Bordur\u0103",
"Constrain proportions": "Constr\u00e2nge propor\u021biile",
"Vertical space": "Spa\u021biu vertical",
"Image description": "Descrierea imaginii",
"Style": "Stil",
"Dimensions": "Dimensiuni",
"Insert image": "Inserare imagine",
"Zoom in": "M\u0103rire",
"Contrast": "Contrast",
"Back": "\u00cenapoi",
"Gamma": "Gamma",
"Flip horizontally": "R\u0103stoarn\u0103 orizontal",
"Resize": "Redimensionare",
"Sharpen": "Accentuare",
"Zoom out": "Mic\u015forare",
"Image options": "Op\u021biuni imagine",
"Apply": "Aplicare",
"Brightness": "Str\u0103lucire",
"Rotate clockwise": "Rotire \u00een sens orar",
"Rotate counterclockwise": "Rotire \u00een sens antiorar",
"Edit image": "Editare imagine",
"Color levels": "Niveluri de culoare",
"Crop": "Decupare",
"Orientation": "Orientare",
"Flip vertically": "R\u0103stoarn\u0103 vertical",
"Invert": "Inversare",
"Insert date\/time": "Insereaz\u0103 data\/ora",
"Remove link": "\u0218terge link-ul",
"Url": "Url",
"Text to display": "Text de afi\u0219at",
"Anchors": "Ancore",
"Insert link": "Inserare link",
"New window": "Fereastr\u0103 nou\u0103",
"None": "Niciuna",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL-ul introdus pare s\u0103 fie o adres\u0103 web. Dori\u021bi s\u0103 ad\u0103uga\u021bi prefixul http:\/\/?",
"Target": "\u021aint\u0103",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL-ul introdus pare s\u0103 fie o adres\u0103 de e-mail. Dori\u021bi s\u0103 ad\u0103uga\u021bi prefixul necesar mailto:?",
"Insert\/edit link": "Inserare\/editare link",
"Insert\/edit video": "Inserare\/editare video",
"Poster": "Poster",
"Alternative source": "Surs\u0103 alternativ\u0103",
"Paste your embed code below:": "Insera\u021bi codul mai jos:",
"Insert video": "Inserare video",
"Embed": "Embed",
"Nonbreaking space": "Spa\u021biu neseparator",
"Page break": "\u00centrerupere de pagin\u0103",
"Paste as text": "Lipe\u015fte ca text",
"Preview": "Examinare",
"Print": "Imprimare",
"Save": "Salvare",
"Could not find the specified string.": "Nu am putut g\u0103si \u0219irul specificat.",
"Replace": "\u00cenlocuire",
"Next": "Urm\u0103torul",
"Whole words": "Doar cuv\u00e2ntul \u00eentreg",
"Find and replace": "G\u0103sire \u015fi \u00eenlocuire",
"Replace with": "\u00cenlocuire cu:",
"Find": "G\u0103sire",
"Replace all": "\u00cenlocuie\u015fte toate",
"Match case": "Distinge majuscule\/minuscule",
"Prev": "Precedentul",
"Spellcheck": "Verificare ortografic\u0103",
"Finish": "Finalizare",
"Ignore all": "Ignor\u0103 toate",
"Ignore": "Ignorare",
"Add to Dictionary": "Ad\u0103ugare \u00een dic\u0163ionar",
"Insert row before": "Insereaz\u0103 \u00eenainte de linie",
"Rows": "R\u00e2nduri",
"Height": "\u00cen\u0103l\u0163ime",
"Paste row after": "Lipe\u015fte linie dup\u0103",
"Alignment": "Aliniere",
"Border color": "Culoare bordur\u0103",
"Column group": "Grup de coloane",
"Row": "Linie",
"Insert column before": "Insereaz\u0103 \u00eenainte de coloan\u0103",
"Split cell": "\u00cemp\u0103r\u021bire celule",
"Cell padding": "Spa\u021biere",
"Cell spacing": "Spa\u021biere celule",
"Row type": "Tip de linie",
"Insert table": "Insereaz\u0103 tabel\u0103",
"Body": "Corp",
"Caption": "Legend\u0103",
"Footer": "Subsol",
"Delete row": "\u0218terge linia",
"Paste row before": "Lipe\u015fte \u00eenainte de linie",
"Scope": "Arie",
"Delete table": "\u0218terge tabel\u0103",
"H Align": "Aliniere H",
"Top": "Sus",
"Header cell": "Antet celul\u0103",
"Column": "Coloan\u0103",
"Row group": "Grup de linii",
"Cell": "Celul\u0103",
"Middle": "Prenume 2",
"Cell type": "Tip celul\u0103",
"Copy row": "Copiaz\u0103 linie",
"Row properties": "Propriet\u0103\u021bi linie",
"Table properties": "Propriet\u0103\u021bi tabel\u0103",
"Bottom": "Jos",
"V Align": "Aliniere V",
"Header": "Antet",
"Right": "Dreapta",
"Insert column after": "Insereaz\u0103 dup\u0103 coloan\u0103",
"Cols": "Coloane",
"Insert row after": "Insereaz\u0103 dup\u0103 linie",
"Width": "L\u0103\u0163ime",
"Cell properties": "Propriet\u0103\u021bi celul\u0103",
"Left": "St\u00e2nga",
"Cut row": "Taie linie",
"Delete column": "\u0218terge coloana",
"Center": "Centru",
"Merge cells": "\u00cembinare celule",
"Insert template": "Insereaz\u0103 \u0219ablon",
"Templates": "\u015eabloane",
"Background color": "Culoare fundal",
"Custom...": "Personalizat...",
"Custom color": "Culoare personalizat\u0103",
"No color": "F\u0103r\u0103 culoare",
"Text color": "Culoare text",
"Show blocks": "Afi\u0219are blocuri",
"Show invisible characters": "Afi\u0219are caractere invizibile",
"Words: {0}": "Cuvinte: {0}",
"Insert": "Insereaz\u0103",
"File": "Fi\u015fier",
"Edit": "Editare",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zon\u0103 cu Rich Text. Apas\u0103 ALT-F9 pentru meniu. Apas\u0103 ALT-F10 pentru bara de instrumente. Apas\u0103 ALT-0 pentru ajutor",
"Tools": "Instrumente",
"View": "Vizualizare",
"Table": "Tabel\u0103",
"Format": "Format"
});
