/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014 Zimbra, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: http://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.
 * All portions of the code are Copyright (C) 2014 Zimbra, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('sl_SI',{
"Cut": "Izre\u017ei",
"Heading 5": "Naslov 5",
"Header 2": "Naslov 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Va\u0161 brskalnik ne dopu\u0161\u010da direktnega dostopa do odlo\u017ei\u0161\u010da. Uporabite kombinacijo bli\u017enji\u010dnih tipk Ctrl+X\/C\/V na tipkovnici.",
"Heading 4": "Naslov 4",
"Div": "Div",
"Heading 2": "Naslov 2",
"Paste": "Prilepi",
"Close": "Zapri",
"Font Family": "Dru\u017eina pisav",
"Pre": "Pre",
"Align right": "Desno poravnano",
"New document": "Nov dokument",
"Blockquote": "Dalj\u0161i citat",
"Numbered list": "O\u0161tevil\u010den seznam",
"Heading 1": "Naslov 1",
"Headings": "Podnaslovi",
"Increase indent": "Pove\u010daj zamik",
"Formats": "Oblika",
"Headers": "Naslovi",
"Select all": "Izberi vse",
"Header 3": "Naslov 3",
"Blocks": "Bloki",
"Undo": "Razveljavi",
"Strikethrough": "Pre\u010drtano",
"Bullet list": "Seznam s to\u010dkami",
"Header 1": "Naslov 1",
"Superscript": "Nadpisano",
"Clear formatting": "Odstrani oblikovanje",
"Font Sizes": "Velikosti pisave",
"Subscript": "Podpisano",
"Header 6": "Naslov 6",
"Redo": "Ponovi",
"Paragraph": "Odstavek",
"Ok": "V redu",
"Bold": "Krepko",
"Code": "Koda",
"Italic": "Le\u017ee\u010de",
"Align center": "Sredinsko poravnano",
"Header 5": "Naslov 5",
"Heading 6": "Naslov 6",
"Heading 3": "Naslov 3",
"Decrease indent": "Zmanj\u0161aj zamik",
"Header 4": "Naslov 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Odlagali\u0161\u010de je zdaj v na\u010dinu golega besedila. Vsebina bo preslikana kot golo besedilo brez oblike, dokler te mo\u017enosti ne izklju\u010dite.",
"Underline": "Pod\u010drtaj",
"Cancel": "Prekli\u010di",
"Justify": "Obojestranska poravnava",
"Inline": "V vrstici",
"Copy": "Kopiraj",
"Align left": "Levo poravnano",
"Visual aids": "Vizualni pripomo\u010dki",
"Lower Greek": "Male gr\u0161ke \u010drke",
"Square": "Kvadratek",
"Default": "Privzeto",
"Lower Alpha": "Mala alfa",
"Circle": "Krog",
"Disc": "Disk",
"Upper Alpha": "Velika alfa",
"Upper Roman": "Velike rimske",
"Lower Roman": "Male rimske",
"Name": "Ime",
"Anchor": "Zaznamek",
"You have unsaved changes are you sure you want to navigate away?": "Imate neshranjene spremembe. Ste prepri\u010dani, da \u017eelite zapustiti stran?",
"Restore last draft": "Obnovi zadnji osnutek",
"Special character": "Posebni znak",
"Source code": "Izvorna koda",
"B": "B",
"R": "R",
"G": "G",
"Color": "Barva",
"Right to left": "Od desne proti levi",
"Left to right": "Od leve proti desni",
"Emoticons": "\u010custveni simboli",
"Robots": "Robotki",
"Document properties": "Lastnosti dokumenta",
"Title": "Naslov",
"Keywords": "Klju\u010dne besede",
"Encoding": "Kodiranje",
"Description": "Opis",
"Author": "Avtor",
"Fullscreen": "Celozaslonski",
"Horizontal line": "Vodoravna \u010drta",
"Horizontal space": "Vodoravni prostor",
"Insert\/edit image": "Vstavi\/uredi sliko",
"General": "Splo\u0161no",
"Advanced": "Napredno",
"Source": "Vir",
"Border": "Obroba",
"Constrain proportions": "Omeji razmerje",
"Vertical space": "Navpi\u010dni prostor",
"Image description": "Opis slike",
"Style": "Slog",
"Dimensions": "Dimenzije",
"Insert image": "Vnesi sliko",
"Zoom in": "Pribli\u017eaj",
"Contrast": "Kontrast",
"Back": "Nazaj",
"Gamma": "Gama",
"Flip horizontally": "Obrni vodoravno",
"Resize": "Spremeni velikost",
"Sharpen": "Izostri",
"Zoom out": "Pomanj\u0161aj",
"Image options": "Slikovne mo\u017enosti",
"Apply": "Uporabi",
"Brightness": "Svetlost",
"Rotate clockwise": "Zasuk v smeri urinega kazalca",
"Rotate counterclockwise": "Zasuk v nasprotni smeri od urinega kazalca",
"Edit image": "Uredi sliko",
"Color levels": "Barvne ravni",
"Crop": "Obre\u017ei",
"Orientation": "Usmerjenost",
"Flip vertically": "Obrni navpi\u010dno",
"Invert": "Preobrni",
"Insert date\/time": "Vstavi datum\/\u010das",
"Remove link": "Odstrani povezavo",
"Url": "Url",
"Text to display": "Besedilo za prikaz",
"Anchors": "Zaznamki",
"Insert link": "Vstavi povezavo",
"New window": "Novo okno",
"None": "Brez",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Vneseni URL predstavlja zunanjo povezavo. Ali \u017eelite dodati potrebno http:\/\/ predpono?",
"Target": "Cilj",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Vneseni URL predstavlja e-po\u0161tni naslov. Ali \u017eelite dodati potrebno mailto: predpono?",
"Insert\/edit link": "Vstavi\/uredi povezavo",
"Insert\/edit video": "Vstavi\/uredi video",
"Poster": "Poster",
"Alternative source": "Nadomestni vir",
"Paste your embed code below:": "Spodaj prilepite kodo za vdelavo:",
"Insert video": "Vstavi video",
"Embed": "Vdelaj",
"Nonbreaking space": "Nedeljivi presledek",
"Page break": "Prelom strani",
"Paste as text": "Prilepi kot besedilo",
"Preview": "Predogled",
"Print": "Natisni",
"Save": "Shrani",
"Could not find the specified string.": "Navedenega niza ni bilo mogo\u010de najti.",
"Replace": "Zamenjaj",
"Next": "Naprej",
"Whole words": "Cele besede",
"Find and replace": "Najdi in zamenjaj",
"Replace with": "Zamenjaj z:",
"Find": "Najdi",
"Replace all": "Zamenjaj vse",
"Match case": "Razlikovanje velikih in malih \u010drk",
"Prev": "Nazaj",
"Spellcheck": "Preverjanje \u010drkovanja",
"Finish": "Dokon\u010daj",
"Ignore all": "Prezri vse",
"Ignore": "Prezri",
"Add to Dictionary": "Dodaj v slovar",
"Insert row before": "Vstavi vrstico pred",
"Rows": "Vrstice",
"Height": "Vi\u0161ina",
"Paste row after": "Prilepi vrstico za",
"Alignment": "Poravnava",
"Border color": "Barva obrobe",
"Column group": "Zdru\u017eevanje stolpcev",
"Row": "Vrstica",
"Insert column before": "Vstavi stolpec pred",
"Split cell": "Razdeli celico",
"Cell padding": "Odmike med celicami",
"Cell spacing": "Razmik med celicami",
"Row type": "Tip vrstice",
"Insert table": "Vstavi tabelo",
"Body": "Telo",
"Caption": "Napis",
"Footer": "Noga",
"Delete row": "Izbri\u0161i vrstico",
"Paste row before": "Prilepi vrstico pred",
"Scope": "Obseg",
"Delete table": "Izbri\u0161i tabelo",
"H Align": "Vodoravna poravnava",
"Top": "Zgoraj",
"Header cell": "Celica glave",
"Column": "Stolpec",
"Row group": "Zdru\u017eevanje vrstic",
"Cell": "Celica",
"Middle": "Srednja",
"Cell type": "Tip celice",
"Copy row": "Kopiraj vrstico",
"Row properties": "Lastnosti vrstice",
"Table properties": "Lastnosti tabele",
"Bottom": "Spodaj",
"V Align": "Navpi\u010dna poravnava",
"Header": "Glava",
"Right": "Desno",
"Insert column after": "Vstavi stolpec za",
"Cols": "Stolpci",
"Insert row after": "Vstavi vrstico za",
"Width": "\u0160irina",
"Cell properties": "Lastnosti celice",
"Left": "Levo",
"Cut row": "Izre\u017ei vrstico",
"Delete column": "Izbri\u0161i stolpec",
"Center": "Sredina",
"Merge cells": "Spoji celice",
"Insert template": "Vstavi predlogo",
"Templates": "Predloge",
"Background color": "Barva ozadja",
"Custom...": "Po meri ...",
"Custom color": "Barva po meri",
"No color": "Brezbarvno",
"Text color": "Barva besedila",
"Show blocks": "Prika\u017ei bloke",
"Show invisible characters": "Prika\u017ei nevidne znake",
"Words: {0}": "Besede: {0}",
"Insert": "Vstavi",
"File": "Datoteka",
"Edit": "Uredi",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Obmo\u010dje obogatenega besedila. Pritisnite ALT-F9 za meni. Pritisnite ALT-F10 za orodno vrstico. Pritisnite ALT-0 za pomo\u010d",
"Tools": "Orodja",
"View": "Ogled",
"Table": "Tabela",
"Format": "Oblika"
});
