/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Web Client
 * Copyright (C) 2014, 2016 Synacor, Inc.
 *
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at: https://www.zimbra.com/license
 * The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide for limited attribution
 * for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is Zimbra Open Source Web Client.
 * The Initial Developer of the Original Code is Zimbra, Inc.  All rights to the Original Code were
 * transferred by Zimbra, Inc. to Synacor, Inc. on September 14, 2015.
 *
 * All portions of the code are Copyright (C) 2014, 2016 Synacor, Inc. All Rights Reserved.
 * ***** END LICENSE BLOCK *****
 */
tinymce.addI18n('sv_SE',{
"Cut": "Klipp ut",
"Heading 5": "Rubrik 5",
"Header 2": "Rubrik 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Din webbl\u00e4sare st\u00f6djer inte direkt \u00e5tkomst till urklipp. Anv\u00e4nd i st\u00e4llet kortkommandona Ctrl+X\/C\/V.",
"Heading 4": "Rubrik 4",
"Div": "Div",
"Heading 2": "Rubrik 2",
"Paste": "Klistra in",
"Close": "St\u00e4ng",
"Font Family": "Teckensnitt",
"Pre": "Pre",
"Align right": "H\u00f6gerjustera",
"New document": "Nytt dokument",
"Blockquote": "Blockcitat",
"Numbered list": "Numrerad lista",
"Heading 1": "Rubrik 1",
"Headings": "Rubriker",
"Increase indent": "\u00d6ka indrag",
"Formats": "Format",
"Headers": "Rubriker",
"Select all": "Markera allt",
"Header 3": "Rubrik 3",
"Blocks": "Block",
"Undo": "\u00c5ngra",
"Strikethrough": "Genomstruken",
"Bullet list": "Punktlista",
"Header 1": "Rubrik 1",
"Superscript": "Upph\u00f6jt",
"Clear formatting": "Rensa formatering",
"Font Sizes": "Teckensnittsstorlekar",
"Subscript": "Neds\u00e4nkt",
"Header 6": "Rubrik 6",
"Redo": "G\u00f6r om",
"Paragraph": "Stycke",
"Ok": "OK",
"Bold": "Fet",
"Code": "Kod",
"Italic": "Kursiv",
"Align center": "Centrera texten",
"Header 5": "Rubrik 5",
"Heading 6": "Rubrik 6",
"Heading 3": "Rubrik 3",
"Decrease indent": "Minska indrag",
"Header 4": "Rubrik 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Klistra in \u00e4r nu i l\u00e4get f\u00f6r oformaterad text. Inneh\u00e5ll kommer att klistras in som oformaterad text tills du sl\u00e5r av detta l\u00e4ge.",
"Underline": "Understruken",
"Cancel": "Avbryt",
"Justify": "Justera",
"Inline": "Relativ",
"Copy": "Kopiera",
"Align left": "V\u00e4nsterjustera",
"Visual aids": "Visuella hj\u00e4lpmedel",
"Lower Greek": "Grekiska gemener",
"Square": "Fyrkant",
"Default": "Ange som standard",
"Lower Alpha": "Alfa gemener",
"Circle": "Cirkel",
"Disc": "Disk",
"Upper Alpha": "Alfa versaler",
"Upper Roman": "Romerska versaler",
"Lower Roman": "Romerska gemener",
"Name": "Namn",
"Anchor": "F\u00e4stpunkt",
"You have unsaved changes are you sure you want to navigate away?": "Du har osparade \u00e4ndringar, vill du \u00e4nd\u00e5 navigera bort?",
"Restore last draft": "\u00c5terst\u00e4ll senaste utkast",
"Special character": "Specialtecken",
"Source code": "K\u00e4llkod",
"B": "B",
"R": "R",
"G": "G",
"Color": "F\u00e4rg",
"Right to left": "H\u00f6ger till v\u00e4nster",
"Left to right": "V\u00e4nster till h\u00f6ger",
"Emoticons": "Uttryckssymboler",
"Robots": "Robotar",
"Document properties": "Dokumentegenskaper",
"Title": "Titel",
"Keywords": "Nyckelord",
"Encoding": "Kodning",
"Description": "Beskrivning",
"Author": "F\u00f6rfattare",
"Fullscreen": "Helsk\u00e4rm",
"Horizontal line": "V\u00e5gr\u00e4t linje",
"Horizontal space": "V\u00e5gr\u00e4tt avst\u00e5nd",
"Insert\/edit image": "Infoga\/redigera bild",
"General": "Allm\u00e4nt",
"Advanced": "Avancerat",
"Source": "K\u00e4lla",
"Border": "Ram",
"Constrain proportions": "Begr\u00e4nsa proportioner",
"Vertical space": "Lodr\u00e4tt avst\u00e5nd",
"Image description": "Bildbeskrivning",
"Style": "Stil",
"Dimensions": "M\u00e5tt",
"Insert image": "Infoga bild",
"Zoom in": "Zooma in",
"Contrast": "Kontrast",
"Back": "Bak\u00e5t",
"Gamma": "Gamma",
"Flip horizontally": "V\u00e4nd v\u00e5gr\u00e4tt",
"Resize": "\u00c4ndra storlek",
"Sharpen": "Sk\u00e4rpa",
"Zoom out": "Zooma ut",
"Image options": "Bildalternativ",
"Apply": "Anv\u00e4nd",
"Brightness": "Ljusstyrka",
"Rotate clockwise": "Rotera medurs",
"Rotate counterclockwise": "Rotera moturs",
"Edit image": "Redigera bild",
"Color levels": "F\u00e4rgniv\u00e5er",
"Crop": "Besk\u00e4r",
"Orientation": "Orientering",
"Flip vertically": "V\u00e4nd lodr\u00e4tt",
"Invert": "Invertera",
"Insert date\/time": "Infoga datum\/tid",
"Remove link": "Ta bort l\u00e4nk",
"Url": "Url",
"Text to display": "Text att visa",
"Anchors": "F\u00e4stpunkter",
"Insert link": "Infoga l\u00e4nk",
"New window": "Nytt f\u00f6nster",
"None": "Inga",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL-adressen du angav verkar vara en extern l\u00e4nk. Vill du l\u00e4gga till prefixet http:\/\/?",
"Target": "M\u00e5l",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL-adressen du angav verkar vara en e-postadress. Vill du l\u00e4gga till det n\u00f6dv\u00e4ndiga prefixet mailto:?",
"Insert\/edit link": "Infoga\/redigera l\u00e4nk",
"Insert\/edit video": "Infoga\/redigera video",
"Poster": "Affisch",
"Alternative source": "Alternativ k\u00e4lla",
"Paste your embed code below:": "Klistra in din inb\u00e4ddningskod nedan:",
"Insert video": "Infoga video",
"Embed": "B\u00e4dda in",
"Nonbreaking space": "H\u00e5rd blanksteg",
"Page break": "Sydbrytning",
"Paste as text": "Klistra in som text",
"Preview": "F\u00f6rhandsgranskning",
"Print": "Skriv ut",
"Save": "Spara",
"Could not find the specified string.": "Kunde inte hitta den angivna str\u00e4ngen.",
"Replace": "Ers\u00e4tt",
"Next": "N\u00e4sta",
"Whole words": "Hela ord",
"Find and replace": "S\u00f6k och ers\u00e4tt",
"Replace with": "Ers\u00e4tt med:",
"Find": "S\u00f6k",
"Replace all": "Ers\u00e4tt alla",
"Match case": "Matcha gemener/versaler",
"Prev": "F\u00f6reg.",
"Spellcheck": "Stavningskontroll",
"Finish": "Slutf\u00f6r",
"Ignore all": "Ignorera alla",
"Ignore": "Ignorera",
"Add to Dictionary": "L\u00e4gg till i ordlista",
"Insert row before": "Infoga rad f\u00f6re",
"Rows": "Rader",
"Height": "H\u00f6jd",
"Paste row after": "Klistra in rad efter",
"Alignment": "Justering",
"Border color": "Ramf\u00e4rg",
"Column group": "Kolumngrupp",
"Row": "Rad",
"Insert column before": "Infoga kolumn f\u00f6re",
"Split cell": "Dela cell",
"Cell padding": "Cellutfyllnad",
"Cell spacing": "Cellavst\u00e5nd",
"Row type": "Radtyp",
"Insert table": "Infoga tabell",
"Body": "Br\u00f6dtext",
"Caption": "Bildtext",
"Footer": "Sidfot",
"Delete row": "Radera rad",
"Paste row before": "Klista in rad f\u00f6re",
"Scope": "Omfattning",
"Delete table": "Radera tabell",
"H Align": "H\u00f6gerjustera",
"Top": "\u00d6verst",
"Header cell": "Inneh\u00e5ller rubrik",
"Column": "Kolumn",
"Row group": "Radgrupp",
"Cell": "Cell",
"Middle": "Mitten",
"Cell type": "Celltyp",
"Copy row": "Kopiera rad",
"Row properties": "Radegenskaper",
"Table properties": "Tabellegenskaper",
"Bottom": "Nederst",
"V Align": "V\u00e4nsterjustering",
"Header": "Rubrik",
"Right": "H\u00f6ger",
"Insert column after": "Infoga kolumn efter",
"Cols": "Kolumner",
"Insert row after": "Infoga rad efter",
"Width": "Bredd",
"Cell properties": "Cellegenskaper",
"Left": "V\u00e4nster",
"Cut row": "Klipp ut rad",
"Delete column": "Radera kolumn",
"Center": "Centrera",
"Merge cells": "Sammanfoga celler",
"Insert template": "Infoga mall",
"Templates": "Mallar",
"Background color": "Bakgrundsf\u00e4rg",
"Custom...": "Anpassad...",
"Custom color": "Anpassad f\u00e4rg",
"No color": "Ingen f\u00e4rg",
"Text color": "Textf\u00e4rg",
"Show blocks": "Visa block",
"Show invisible characters": "Visa osynliga tecken",
"Words: {0}": "Ord: {0}",
"Insert": "Infoga",
"File": "Fil",
"Edit": "Redigera",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "RTF-omr\u00e5de. Tryck ALT-F9 f\u00f6r meny. Tryck ALT-F10 f\u00f6r verktygsf\u00e4lt. Tryck ALT-0 f\u00f6r hj\u00e4lp.",
"Tools": "Verktyg",
"View": "Visa",
"Table": "Tabell",
"Format": "Format"
});
